main: net.natroutter.purgatory.Purgatory
name: Purgatory
version: ${project.version}
author: NATroutter
description: ${project.description}
api-version: 1.16
website: ${project.url}
depend:
  - Citizens
softdepend:
  - Vault
  - WorldGuard